### ISSUE TITLE
[Bug] UI Issues

### ISSUE THREAD

**Issue by huangqg** [kubeagi/agent-portal#53]
### 💻 系统环境 | Operating System

Windows

### 🐛 问题描述 | Bug Description

UI issues

![image](https://github.com/kubeagi/arcadia/assets/5961349/dac12926-a15a-4201-b9d5-40bd02958b7f)

未登录状态需要设计下，这里显示像加载失败
![image](https://github.com/kubeagi/arcadia/assets/5961349/a31396e1-eca2-4747-8bc2-9a4e78bbc290)

**Comment by Vsion** [comment]
![image](https://github.com/kubeagi/agent-portal/assets/11804448/51115eb8-9d65-4d1f-8938-28ec66a7229b)
外层我调整了一下, 里面的分类有bug, 看一下 @linqiqi077
