### ISSUE TITLE
存在私有包，无权限访问私有地址`http://dev-npm.k8s.com.cn/@tenx-ui/bff-client/-/bff-client-0.3.1.tgz:`

### ISSUE THREAD

**Issue by gaoxiu333** [kubeagi/agent-portal#54]
### 环境

**node**：`v20.7.0`
**pnpm**: `8.12.1`

### 复现步骤
1. clone代码到本地
2. 执行`pnpm install` 
报错如下图：
<img width="1066" alt="image" src="https://github.com/kubeagi/agent-portal/assets/24784662/4214bf5b-cb5e-4a07-99da-cb496fda54d6">

**Comment by huangqg** [comment]
@gaoxiu333  先执行下这个，再安装依赖

npm set //dev-npm.k8s.com.cn/:_authToken="pswHLzvzEb0OM8RTvqW6dApj44PF8ZGajEmAVUgeQxs="

**Comment by Carrotzpc** [comment]
内部包正在移除中，可以今天晚点儿或者明天上午再试试

**Comment by Carrotzpc** [comment]
@Vsion 可以替换为这个包 `@yuntijs/bff-client@0.3.3`
