### ISSUE TITLE
[Question] 面试疑问

### ISSUE THREAD

**Issue by xln798** [kubeagi/agent-portal#57]
### 🧐 问题描述 | Proposed Solution

你好，我在求职时hr给我发送了两个github，让我先去解issue或者提issue然后在面试，当我再给他发消息就是未读了，所以我想知道的是，假如我按照他说的，那么公司如何知道是我，并且如何进行下一步的面试呢，git上的用户名都不是姓名

**Comment by Carrotzpc** [comment]
有疑问请直接跟 hr 联系，不要提项目无关的 issue

**Comment by xln798** [comment]
但是hr消息未读 请问你知道这样的面试形式吗 让求职者到github上来 总的有个人出来解释一下吧

**Comment by xln798** [comment]
> 有疑问请直接跟 hr 联系，不要提项目无关的 issue

但是hr消息未读 请问你知道这样的面试形式吗 让求职者到github上来 总的有个人出来解释一下吧
