### ISSUE TITLE
[Bug] UI Bug

### ISSUE THREAD

**Issue by strawferry** [kubeagi/agent-portal#59]
### 💻 系统环境 | Operating System

macOS

### 🐛 问题描述 | Bug Description

从 dark 模式进入,页面会先从白色模式闪变到黑色模式

https://github.com/kubeagi/agent-portal/assets/14286915/67d15cd4-33e2-4beb-890d-7042a82fe768

**Comment by Vsion** [comment]
原因是选择跟随系统时,需要在客户端获取当前访问的终端是否是 dark 导致此问题, 需要修复
