### ISSUE TITLE
[Bug] Opimise the page loading cost

### ISSUE THREAD

**Issue by huangqg** [kubeagi/agent-portal#69]
### 💻 系统环境 | Operating System

macOS

### 🐛 问题描述 | Bug Description

Opimise the page loading cost

![image](https://github.com/kubeagi/agent-portal/assets/5961349/ce6e37e2-29aa-428c-9925-2b9eebef6bf5)

### 🚦 期望结果 | Expected Behavior

open a page with less time < 1s.

**Comment by Vsion** [comment]
/chat/bot/create 临时改为 /agent (https://github.com/kubeagi/agent-portal/pull/68)
