### ISSUE TITLE
[Question] OIDC_SERVER_URL 这个该填什么呢，或者如何绕过oidc认证

### ISSUE THREAD

**Issue by colin404** [kubeagi/agent-portal#85]
### 🧐 问题描述 | Proposed Solution

尝试了以下值都不行：
https://portal.kubeagi.com/oidc
https://kubeagi.com/oidc

**Comment by nkwangleiGIT** [comment]
需要使用部署 u4a-system 的 oidc-server 的地址，一般是通过 ingress 暴露，为 https://<portal.xxx>/oidc
oidc-server 是 基于 dex 构建，支持了基于 User CRD 的认证方式

**Comment by colin404** [comment]
> 需要使用部署 u4a-system 的 oidc-server 的地址，一般是通过 ingress 暴露，为 https://<portal.xxx>/oidc oidc-server 是 基于 dex 构建，支持了基于 User CRD 的认证方式

Thanks！
